#pragma once

#include "NativeGameplayTags.h"

#pragma region Character_Region


#pragma region Character_State

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Free_Roam);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Landing_Impact);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Mantle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Vault);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Ready_To_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Exiting_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Initialize_Wall_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Wall_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Initialize_Wall_Pipe_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Wall_Pipe_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Initialize_Balance_Walk);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Balance_Walk);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Tic_Tac);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Stairs);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Initialize_Slide);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Slide);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_State_Roll);


#pragma endregion


#pragma region Character_Action

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_No_Action);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Free_Roam_Accelerating_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Accelerating_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Normal_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Falling_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Falling_Climb_Slipped);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Climb_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Left_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Right_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Left_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Hop_Right_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Shimmy_180_Shimmy);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Exit_Jump_Forward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Braced_Climb_Exit_Jump_Backward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Accelerating_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Normal_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Falling_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Falling__Climb_Hanging_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Climb_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Hop_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Hop_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Hop_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Shimmy_180_Shimmy);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_FreeHang_Exit_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Corner_Move);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_Start_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_Start_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_L_Jump_F);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_R_Jump_F);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_Left_Jump_90_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_Right_Jump_90_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_L_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Run_R_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Attach_Grounded);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Attach_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Jump_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Jump_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Jump_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Jump_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Fall_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Wall_Pipe_Climb_Up_2_Hand);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Mantle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Accurate_Jump_Start_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Accurate_Jump_Start_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Accurate_Jump_Start_L_Warp);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Accurate_Jump_Start_R_Warp);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Accurate_Jump_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Front_L_Start);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Front_R_Start);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Front_L_Start_Warp);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Front_R_Start_Warp);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_One_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Jump_One_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Walk_90_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Walk_90_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Walk_180);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Walk_Automatic_Hop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Drop_L_Hanging);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Balance_Drop_R_Hanging);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Hanging_Climb_Up_To_Balanced_Walk_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Hanging_Climb_Up_To_Balanced_Walk_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Wall_Vault_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Wall_Vault_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Wall_Vault_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Wall_Vault_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Wall_Vault_Under_Bar);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Wall_Vault_Over_180_Shimmy);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_L_Over_Front_Wall);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_R_Over_Front_Wall);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_L_On_Front_Wall_To_Idle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_L_On_Front_Wall_To_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_R_On_Front_Wall_To_Idle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_R_On_Front_Wall_To_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_L_Over_Right_Wall);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Tic_Tac_R_Over_Left_Wall);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_L_Start);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_R_Start);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_L_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_R_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_L_To_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Slide_R_To_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Unarmed_Crouch_Entry);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Unarmed_Crouch_Exit);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_L_Small_Failed);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_R_Small_Failed);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_L_Large_Failed);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_R_Large_Failed);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_L_Large);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_L_Small);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_R_Large);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Vertical_Wall_Run_R_Small);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_L_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_R_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_L_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_R_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_L_On_Off_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_R_On_Off_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_L_On_Off_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_R_On_Off_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_L_On_Off_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Walking_Step_R_On_Off_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_L_On_Off_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Step_R_On_Off_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Vault_L_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Vault_R_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Jump_Step_On_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Running_Jump_Step_On_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Medium_Vault_L_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Medium_Vault_R_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_High_Vault_L_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_High_Vault_R_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Long_Vault_L_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Long_Vault_R_To_Ground);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Vault_L_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Idle_Vault_R_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Medium_Vault_L_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Medium_Vault_R_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_High_Vault_L_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_High_Vault_R_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Long_Vault_L_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Long_Vault_R_To_Airborne);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Roll_Forward_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Roll_Forward_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Dive_Roll_Forward_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Action_Dive_Roll_Forward_R);




#pragma endregion


#pragma region Character_Direction

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_No_Direction);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Forward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Backward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Forward_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Forward_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Backward_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Direction_Backward_Right);


#pragma endregion


#pragma region Character_Stairs_Direction

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Stairs_Direction_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Stairs_Direction_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Stairs_Direction_Down);

#pragma endregion


#pragma region Character_Climb_Style

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Climb_Style_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Climb_Style_Braced_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Climb_Style_FreeHang);

#pragma endregion


#pragma region Character_Wall_Run

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Wall_Run_Side_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Wall_Run_Side_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Wall_Run_Side_Right);

#pragma endregion


#pragma region Character_Landing

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Landing_Down_Light);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Landing_Down_Impact);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Landing_Down_Front);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Landing_Down_Roll);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Landing_Down_Back_Roll);


#pragma endregion


#pragma region Character_Tic_Tac

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Jump_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Jump_On_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Vault_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Jump_On);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Jump_On_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Vault_On);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Jump_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Reverse_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Speed_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Jump_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Reverse_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Speed_Over);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_L_Jump_Side_Over);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Tic_Tac_R_Jump_Side_Over);

#pragma endregion


#pragma region Character_Slide

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Slide_Side_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Slide_Side_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_Slide_Side_Right);

#pragma endregion


#pragma endregion


