#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Free_Roam);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Ready_To_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Wall_Run_Initialize);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Wall_Run);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Mantle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_State_Vault);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_No_Action);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Accelerating_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Normal_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Falling_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Falling_Climb_Slipped);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Climb_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Left_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Right_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Left_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Hop_Right_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Shimmy_180_Shimmy);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Braced_Climb_Exit_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Accelerating_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Normal_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Falling_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Falling__Climb_Hanging_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Climb_Up);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Hop_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Hop_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Hop_Down);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Shimmy_180_Shimmy);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_FreeHang_Exit_Jump);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Corner_Move);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_Start_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_Start_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_L_Jump_F);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_R_Jump_F);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_Left_Jump_90_R);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_Right_Jump_90_L);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_L_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Wall_Run_R_Finish);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Mantle);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_Low_Vault);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Action_High_Vault);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_No_Direction);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Forward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Backward);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Forward_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Forward_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Backward_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Direction_Backward_Right);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Climb_Style_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Climb_Style_Braced_Climb);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Climb_Style_FreeHang);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Wall_Run_Side_None);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Wall_Run_Side_Left);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Parkour_Wall_Run_Side_Right);